### ISSUE TITLE
 Freeze Stick has been changed to a higher value

### ISSUE THREAD

**Issue by excaliburkim** [el211/AdvancedFreezeStick#1]
Thank you for making it. I will use it well.
There is an error as below:

1. Place the Freeze Stick in the item_frame.
2. Remove the Freeze Stick from the item_frame.
3. The “remaining usage count” of the Freeze Stick has been changed to a higher value. (ex. 993/999)

**Comment by el211** [comment]
can you pls send a recording of it ?

> Thank you for making it. I will use it well. There is an error as below:
> 
> 1. Place the Freeze Stick in the item_frame.
> 2. Remove the Freeze Stick from the item_frame.
> 3. The “remaining usage count” of the Freeze Stick has been changed to a higher value. (ex. 993/999)

**Comment by el211** [comment]
> Thank you for making it. I will use it well. There is an error as below:
> 
> 1. Place the Freeze Stick in the item_frame.
> 2. Remove the Freeze Stick from the item_frame.
> 3. The “remaining usage count” of the Freeze Stick has been changed to a higher value. (ex. 993/999)

Issue is fixed ! 
Download trhe latest plugin from my spigot :)

Pls make sure to leave a positive feedback , lots of stick are gonna be on my page tonight and tomorrow :)

**Comment by excaliburkim** [comment]
https://a-r-c.kr/mc/4/2024_03_21_17_22_42_865.mp4

**Comment by excaliburkim** [comment]
Oh, You've fixed it!
Let's test it!

**Comment by el211** [comment]
> https://a-r-c.kr/mc/4/2024_03_21_17_22_42_865.mp4
for some reason yur video is not working , but i understood what you mean 
I have fixed it 
check spigot update :)

**Comment by el211** [comment]
> Oh, You've fixed it!
> I will test it!

yep let me know how it goes 👍 and pls don't forget to leave a positive feedback on spigot :)
I am having more stick pon my spigot page by tonight

**Comment by excaliburkim** [comment]
I tested it, and the same problem appears.

It appears like this:
998/999

I am very excited for the other sticks!!!!!!

**Comment by excaliburkim** [comment]
http://a-r-c.kr/mc/4/2024_03_21_17_22_42_865.mp4

**Comment by el211** [comment]
> I tested it, and the same problem appears.
> 
> It appears like this: 998/999
> 
> I am very excited for the other sticks!!!!!!

Can you show me your config?

**Comment by excaliburkim** [comment]
# AdvancedFreezeStick Plugin Configuration
max_uses: 999
stick_name: "&bFreezing Stick"
stick_lore:
  - "&7Right-click to freeze a player!"
  - "&7Remaining Uses: &e%d%/%d%"
custom_model_data: 998
cooldown: 30
freezing_time: 1

**Comment by excaliburkim** [comment]
The configuration file is as above.

**Comment by el211** [comment]
let me know your server version 
and pls make sure you used the new jar I am gonna ping upload it for you again here on Mediafire link  
 https://www.mediafire.com/file/kura1qthhvtrz3d/AdvancedFreezeStick-1.0-SNAPSHOT.jar/file

and won't forget to delete all jar and put the new one then restart your server

**Comment by excaliburkim** [comment]
/version
Current: git-Purpur-2159 (MC: 1.20.4)*

The result is as above.

**Comment by excaliburkim** [comment]
Yes, I used 1.2

**Comment by excaliburkim** [comment]
I'll try again with the new file you provided.

**Comment by el211** [comment]
https://github.com/el211/AdvancedFreezeStick/assets/86126606/5a6145cd-ec86-463a-9297-09ba5ebb6f01

i am also runnig same version server as you and same plugin its not being reproduced on my side

**Comment by excaliburkim** [comment]
The new plugin you provided works well!
thank you! :)

**Comment by el211** [comment]
> The new plugin you provided works well!
> thank you! :)

Great 🥉
